### ISSUE TITLE
License for parallel-hairy-octo-batman/UPPAAL/uppaal-4.0.13/ ?

### ISSUE THREAD

**Issue by mikucionisaau** [kattfisk/parallel-hairy-octo-batman#1]
Hi,
Do you have a license to distribute Uppaal in parallel-hairy-octo-batman/UPPAAL/uppaal-4.0.13/ ?
The license is quite explicit that distribution needs a written permission.
Marius

**Comment by kattfisk** [comment]
Oops, didn't think of that when I made the repo public. It's been removed.
